-- Stocks Table Schema
CREATE TABLE IF NOT EXISTS public.stocks (
    ticker TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT,
    market_cap TEXT,
    price NUMERIC NOT NULL,
    change NUMERIC,
    change_percent NUMERIC,
    volatility TEXT,
    dividend_yield NUMERIC,
    metaphors JSONB,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Settings
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.stocks FOR SELECT USING (true);

-- Seed Data
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('005930', '삼성전자', '반도체', '400조', 72500, 1500, 2.11, 'low', 2.5, '{"INTJ": "기술 제국의 설계자. 치밀한 전략으로 세계를 정복한다.", "INTP": "반도체의 거장. 논리로 만들어낸 완벽한 시스템.", "ENTJ": "글로벌 리더. 1등만이 살아남는 전쟁터의 승자.", "ENTP": "끊임없는 혁신. 항상 새로운 도전을 즐기는 거인.", "default": "대한민국을 대표하는 글로벌 기술 기업"}', '{"대형주","우량주","배당주","반도체"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('000660', 'SK하이닉스', '반도체', '100조', 134000, -2000, -1.47, 'medium', 1.2, '{"INTJ": "메모리의 심장. 데이터 시대의 핵심 인프라.", "ENTJ": "반도체 전쟁의 두 번째 주자. 1등을 노리는 야망.", "default": "글로벌 메모리 반도체 강자"}', '{"대형주","성장주","반도체","AI"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('035420', 'NAVER', '인터넷', '50조', 189000, 3500, 1.89, 'medium', 0.3, '{"INTJ": "정보의 성. 지식을 체계화하는 디지털 도서관.", "INFJ": "연결의 다리. 사람과 정보를 이어주는 가치.", "ENFP": "무한한 가능성. 새로운 서비스가 샘솟는 플랫폼.", "default": "대한민국 No.1 인터넷 플랫폼"}', '{"대형주","플랫폼","IT","AI"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('035720', '카카오', '인터넷', '20조', 45600, 800, 1.78, 'medium', 0, '{"ENFP": "일상의 친구. 우리 생활에 스며든 노란 말풍선.", "ESFP": "재미있는 세상. 카톡, 카뱅, 카카오T까지!", "default": "생활 밀착형 플랫폼 기업"}', '{"대형주","플랫폼","IT","핀테크"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('068270', '셀트리온', '바이오', '30조', 156000, 2500, 1.63, 'high', 0.2, '{"INFJ": "생명을 살리는 기업. 바이오시밀러로 의료 접근성을 높이다.", "INTJ": "과학의 승리. 연구 끝에 피어난 결실.", "default": "글로벌 바이오시밀러 선도 기업"}', '{"바이오","성장주","헬스케어"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('207940', '삼성바이오로직스', '바이오', '70조', 850000, 15000, 1.8, 'medium', 0, '{"ISTJ": "안정적인 성장. 검증된 CMO 사업 모델.", "INTJ": "바이오 인프라의 거인. 세계 1위를 향한 여정.", "default": "글로벌 바이오의약품 위탁생산(CMO) 1위"}', '{"바이오","대형주","헬스케어","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('005490', 'POSCO홀딩스', '철강', '25조', 320000, -5000, -1.54, 'medium', 3.5, '{"ISTJ": "철의 기둥. 대한민국 산업화의 상징.", "ESTJ": "효율의 대명사. 철강에서 2차전지까지.", "default": "철강에서 친환경 소재까지"}', '{"대형주","배당주","철강","2차전지"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('051910', 'LG화학', '화학', '35조', 450000, 8000, 1.81, 'medium', 1.8, '{"INTJ": "화학의 미래를 그리다. 2차전지 핵심 소재.", "ENTJ": "배터리 전쟁의 핵심 플레이어.", "default": "화학에서 배터리까지, 다각화된 거인"}', '{"대형주","2차전지","화학","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('006400', '삼성SDI', '2차전지', '30조', 420000, 5000, 1.2, 'high', 0.5, '{"ENTJ": "에너지 저장의 리더. 전기차 시대의 핵심.", "INTJ": "기술로 미래를 준비하다.", "default": "글로벌 2차전지 및 전자재료 기업"}', '{"대형주","2차전지","성장주","전기차"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('000270', '기아', '자동차', '35조', 85000, 1200, 1.43, 'medium', 4.0, '{"ESTJ": "효율의 아이콘. 디자인과 성능의 균형.", "ISFJ": "안전한 이동. 가족을 위한 차.", "default": "글로벌 자동차 브랜드"}', '{"대형주","배당주","자동차","전기차"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('247540', '에코프로비엠', '2차전지', '15조', 180000, 12000, 7.14, 'very-high', 0, '{"ENTP": "폭발적 성장! 2차전지 소재의 슈퍼스타.", "ESTP": "가즈아~! 급등의 아이콘.", "ENFP": "꿈을 현실로! 친환경 미래의 주역.", "default": "2차전지 양극재 선도 기업"}', '{"2차전지","성장주","고변동성","친환경"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('086520', '에코프로', '2차전지', '10조', 95000, 5500, 6.15, 'very-high', 0, '{"ESTP": "롤러코스터! 스릴을 즐기는 투자자를 위한.", "ENTP": "변동성이 곧 기회! 과감한 베팅.", "default": "2차전지 소재 지주회사"}', '{"2차전지","성장주","고변동성","지주회사"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('326030', 'SK바이오팜', '제약', '5조', 85000, 1800, 2.16, 'high', 0, '{"INFJ": "생명을 위한 연구. 신약 개발의 희망.", "INTP": "과학적 도전. 수년간의 연구 끝에 빛나는 결실.", "default": "신약 개발 전문 제약사"}', '{"바이오","성장주","신약","헬스케어"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('352820', '하이브', '엔터', '10조', 200000, 4500, 2.3, 'high', 0, '{"ENFP": "꿈의 무대! K-POP의 글로벌 제국.", "ESFP": "반짝반짝! 스타를 만드는 공장.", "ISFP": "감성과 예술. 음악으로 세상을 감동시키다.", "default": "BTS 소속사, 글로벌 K-POP 리더"}', '{"엔터","성장주","K-POP","콘텐츠"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('041510', '에스엠', '엔터', '1조', 82000, 1500, 1.86, 'high', 0.5, '{"ISFP": "K-POP의 산실. 아이돌 시스템의 창시자.", "ESFP": "끝없는 히트곡! 엔터의 클래식.", "default": "K-POP 1세대 엔터테인먼트"}', '{"엔터","K-POP","콘텐츠"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('122870', 'YG엔터테인먼트', '엔터', '8000억', 52000, 800, 1.56, 'high', 0, '{"ISFP": "힙합 DNA. 음악으로 개성을 표현하다.", "ESFP": "스타일리시! 독보적인 아티스트 라인업.", "default": "블랙핑크 소속사"}', '{"엔터","K-POP","콘텐츠"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('035900', 'JYP엔터테인먼트', '엔터', '1.2조', 68000, 1200, 1.8, 'high', 0.8, '{"ENFJ": "함께 성장하는 아티스트. 팀워크의 힘.", "ESFP": "트와이스의 기적! 글로벌 팬덤.", "default": "트와이스, 스트레이키즈 소속사"}', '{"엔터","K-POP","콘텐츠","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('036570', '엔씨소프트', '게임', '10조', 185000, -3500, -1.86, 'high', 1.2, '{"INTP": "게임 설계의 장인. 리니지 신화의 창조자.", "INTJ": "IP의 힘. 오랜 시간 쌓아온 브랜드 가치.", "default": "리니지 시리즈 개발사"}', '{"게임","IT","콘텐츠","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('251270', '넷마블', '게임', '5조', 48000, 950, 2.02, 'high', 0, '{"ENFP": "다양한 게임! 끊임없는 신작 출시.", "ENTP": "글로벌 도전! 해외 시장 개척.", "default": "모바일 게임 강자"}', '{"게임","IT","콘텐츠","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('263750', '펄어비스', '게임', '1.5조', 42000, 1800, 4.48, 'very-high', 0, '{"ISTP": "기술력의 결정체. 검은사막의 그래픽.", "ESTP": "빠른 액션! 박진감 넘치는 게임.", "default": "검은사막 개발사"}', '{"게임","IT","콘텐츠","고변동성"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('112040', '위메이드', '게임', '2조', 38000, 2500, 7.04, 'very-high', 0, '{"ENTP": "블록체인 게임의 선구자! P2E의 미래.", "ESTP": "고위험 고수익! 급등락의 롤러코스터.", "default": "미르4, 위믹스 플랫폼"}', '{"게임","블록체인","고변동성","신산업"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('293490', '카카오게임즈', '게임', '3조', 25000, 450, 1.83, 'high', 0, '{"ENFP": "카카오의 게임 플랫폼! 다양한 IP.", "ESFP": "재미있는 게임들! 가볍게 즐기는.", "default": "게임 퍼블리싱 및 개발"}', '{"게임","IT","플랫폼","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('377300', '카카오페이', '핀테크', '5조', 32000, 850, 2.73, 'high', 0, '{"ENTP": "결제의 혁신! 간편함의 끝.", "ENFP": "일상의 편리함! 터치 한 번으로.", "default": "간편결제 플랫폼"}', '{"핀테크","IT","플랫폼","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('402340', 'SK스퀘어', '지주회사', '8조', 52000, 1200, 2.36, 'medium', 0.8, '{"INTJ": "미래 투자의 포트폴리오. ICT 지주회사.", "ENTJ": "전략적 투자! 성장 산업에 집중.", "default": "SK하이닉스 지분 보유 지주회사"}', '{"지주회사","IT","반도체","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('055550', '신한지주', '금융', '20조', 42000, 500, 1.2, 'low', 5.5, '{"ISTJ": "안정의 상징. 검증된 금융 그룹.", "ISFJ": "안심할 수 있는 배당. 든든한 수익.", "default": "대한민국 대표 금융지주"}', '{"금융","배당주","대형주","안정주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('034730', 'SK', '지주회사', '15조', 175000, 2500, 1.45, 'low', 4.0, '{"ISTJ": "다각화된 거인. 에너지에서 반도체까지.", "ESTJ": "체계적인 그룹 경영. 안정적 성장.", "default": "SK그룹 지주회사"}', '{"지주회사","배당주","대형주","안정주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('018260', '삼성에스디에스', 'IT서비스', '10조', 145000, 1500, 1.05, 'low', 2.0, '{"ISTJ": "시스템의 안정. IT 인프라의 핵심.", "INTJ": "디지털 전환의 파트너. 기업 IT의 핵심.", "default": "삼성그룹 IT서비스 기업"}', '{"IT","대형주","안정주","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('032640', 'LG유플러스', '통신', '5조', 11500, 150, 1.32, 'low', 5.0, '{"ISFJ": "안정적인 배당. 통신의 든든함.", "ISTJ": "필수 인프라. 꾸준한 현금흐름.", "default": "통신 및 미디어 서비스"}', '{"통신","배당주","안정주","5G"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('096770', 'SK이노베이션', '에너지', '8조', 95000, 2000, 2.15, 'medium', 2.5, '{"ENFJ": "친환경 전환의 선두. 그린 에너지로.", "INTJ": "에너지 패러다임의 변화를 준비하다.", "default": "정유에서 배터리까지"}', '{"에너지","2차전지","성장주","친환경"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('003670', '포스코퓨처엠', '2차전지', '12조', 280000, 8000, 2.94, 'high', 0.3, '{"ENTJ": "2차전지 소재의 핵심. 미래를 준비하다.", "INTJ": "철강에서 배터리로. 변신의 성공.", "default": "2차전지 양극재 및 음극재"}', '{"2차전지","성장주","친환경","소재"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('012330', '현대모비스', '자동차부품', '20조', 230000, 3500, 1.55, 'medium', 2.0, '{"ISTJ": "자동차의 심장. 안정적인 부품 공급.", "ESTJ": "효율적인 모듈화. 체계적인 성장.", "default": "현대차그룹 핵심 부품사"}', '{"자동차","부품","대형주","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('028260', '삼성물산', '건설/상사', '18조', 135000, 2000, 1.5, 'low', 1.5, '{"ISTJ": "삼성 그룹의 뿌리. 안정적인 지주 역할.", "ESTJ": "건설에서 패션까지. 다각화된 사업.", "default": "삼성그룹 지주회사 역할"}', '{"건설","대형주","안정주","지주회사"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('105560', 'KB금융', '금융', '25조', 58000, 800, 1.4, 'low', 4.5, '{"ISTJ": "금융의 안정. 검증된 리더십.", "ISFJ": "안심 배당. 가족의 미래를 위한.", "default": "국민은행 지주회사"}', '{"금융","배당주","대형주","안정주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('010140', '삼성중공업', '조선', '8조', 12000, 350, 3.01, 'high', 0, '{"INTP": "저평가된 숨은 보석. 조선 사이클 회복.", "ISTP": "실전 기술력. 대형 선박의 장인.", "default": "LNG선 건조 세계 1위"}', '{"조선","가치주","턴어라운드","수출"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('097950', 'CJ제일제당', '식품', '5조', 285000, 4500, 1.6, 'low', 1.8, '{"ISFJ": "밥상의 안정. 식품의 든든한 선택.", "ISTJ": "필수소비재. 경기와 무관한 안정성.", "default": "식품 및 바이오 기업"}', '{"식품","필수소비재","안정주","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('028050', '삼성엔지니어링', '건설', '5조', 28000, 650, 2.38, 'medium', 1.5, '{"INTP": "저평가 가치주. 수주 회복의 기대.", "ESTJ": "플랜트 건설의 강자. 해외 프로젝트.", "default": "플랜트 건설 전문"}', '{"건설","가치주","수출","플랜트"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('011170', '롯데케미칼', '화학', '4조', 95000, -1500, -1.55, 'medium', 2.0, '{"INTP": "사이클의 바닥. 회복을 기다리는 저평가주.", "ISTJ": "기초 화학의 거인. 장기 관점 투자.", "default": "석유화학 기업"}', '{"화학","가치주","사이클","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('034220', 'LG디스플레이', '디스플레이', '5조', 14500, 250, 1.75, 'high', 0, '{"INTP": "OLED의 선구자. 기술 혁신의 역사.", "ISTP": "기술력의 결정체. 패널 기술의 장인.", "default": "OLED 디스플레이 선도 기업"}', '{"디스플레이","OLED","기술주","턴어라운드"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('000720', '현대건설', '건설', '4조', 38000, 500, 1.33, 'medium', 3.0, '{"ISTJ": "건설 명가. 안정적인 실적 기반.", "ESTJ": "체계적인 프로젝트 관리. 효율성.", "default": "현대차그룹 건설사"}', '{"건설","가치주","배당주","대형주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('003550', 'LG', '지주회사', '12조', 78000, 1000, 1.3, 'low', 3.5, '{"ISTJ": "LG그룹의 중심. 다각화된 포트폴리오.", "ISFJ": "안정적 배당. 오랜 역사의 신뢰.", "default": "LG그룹 지주회사"}', '{"지주회사","배당주","안정주","대형주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('004020', '현대제철', '철강', '5조', 32000, 450, 1.43, 'medium', 2.5, '{"ISTJ": "철강의 기반. 자동차와 건설의 근간.", "INTP": "사이클 저점. 회복을 기다리는 가치주.", "default": "현대차그룹 철강사"}', '{"철강","가치주","사이클","배당주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('005940', 'NH투자증권', '증권', '3조', 12500, 200, 1.63, 'medium', 5.5, '{"ISTJ": "증권의 클래식. 안정적인 수수료 수익.", "ISFJ": "높은 배당. 꾸준한 현금흐름.", "default": "종합 증권사"}', '{"금융","증권","배당주","가치주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('002380', 'KCC', '화학', '3조', 245000, 3500, 1.45, 'low', 2.0, '{"ISTJ": "안정적인 건자재. 오랜 역사의 기업.", "INTP": "숨겨진 가치주. 견고한 재무구조.", "default": "건자재 및 실리콘 기업"}', '{"화학","건자재","가치주","안정주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('066570', 'LG전자', '가전', '15조', 92000, 1500, 1.66, 'medium', 2.0, '{"ISTJ": "가전의 클래식. 안정적인 글로벌 브랜드.", "ESTJ": "효율적인 제품 라인업. 체계적 성장.", "default": "글로벌 가전 및 전장 기업"}', '{"가전","대형주","배당주","전장"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('108860', '셀바스AI', 'AI', '5000억', 8500, 450, 5.59, 'very-high', 0, '{"INTP": "AI의 미래. 음성인식 기술의 선구자.", "ENTP": "신산업 도전! AI 헬스케어의 가능성.", "default": "AI 기반 음성인식 및 헬스케어"}', '{"AI","신산업","고변동성","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('950130', '엔지켐생명과학', '바이오', '5000억', 12000, 850, 7.63, 'very-high', 0, '{"ENTP": "고위험 고수익! 신약 개발의 도박.", "ESTP": "급등락의 스릴! 바이오의 롤러코스터.", "default": "신약 개발 바이오 기업"}', '{"바이오","신약","고변동성","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
INSERT INTO public.stocks (ticker, name, sector, market_cap, price, change, change_percent, volatility, dividend_yield, metaphors, tags) VALUES ('067160', '아프리카TV', '인터넷', '8000억', 85000, 2500, 3.03, 'high', 0.5, '{"ENFP": "1인 미디어의 선구자! 창작자 경제.", "ESFP": "재미있는 콘텐츠! 라이브 스트리밍.", "default": "라이브 스트리밍 플랫폼"}', '{"인터넷","콘텐츠","플랫폼","성장주"}') ON CONFLICT (ticker) DO UPDATE SET price = EXCLUDED.price, change = EXCLUDED.change, change_percent = EXCLUDED.change_percent;
